---
- name: Clean up secret files on control host.
  hosts: localhost
  connection: local
  gather_facts: no
  sudo: no

  tasks:
    - name: Ensure secret variable file is deleted.
      file:
        path: vars/secrets.yml
        state: absent
