---
- include: bootstrap.yml
- include: secure-variables.yml

- name: Set up a fresh environment
  hosts: targets
  sudo: no
  gather_facts: no

  vars_files:
    - vars/aws.yml

  pre_tasks:
    - name: Load secure variables from S3.
      include_vars: vars/secure.yml

  roles:
    - role: base

    - role: zsh
      tags: [ 'zsh' ]

    - role: git

    - role: rvm
      tags: [ 'language' ]

    - role: node
      tags: [ 'language' ]

    - role: password-store
      tags: [ 'private' ]

    - role: chromium
      tags: [ 'gui' ]

    - role: sublime
      tags: [ 'gui' ]

    - role: hipchat
      tags: [ 'gui' ]

- include: cleanup.yml
