---
- include: bootstrap.yml
- include: secure-variables.yml

- name: Set up a fresh environment
  hosts: targets
  sudo: no

  vars_files:
    - vars/aws.yml

  pre_tasks:
    - name: Load secure variables from S3.
      include_vars: vars/secure.yml

    - name: Check to see if X is installed.
      shell: which X
      register: which_x
      ignore_errors: yes

  roles:
    - role: zsh
      tags: [ 'zsh' ]

    - role: git
      tags: [ 'git' ]

    - role: rvm
      tags: [ 'rvm' ]

    - role: node
      tags: [ 'node' ]

    - role: chef
      tags: [ 'chef' ]

    - role: password-store
      tags: [ 'password-store' ]

    - role: chromium
      tags: [ 'chromium' ]
      when: which_x.rc == 0

    - role: sublime
      tags: [ 'sublime' ]
      when: which_x.rc == 0

    - role: hipchat
      tags: [ 'hipchat' ]
      when: which_x.rc == 0

- include: cleanup.yml
