---
- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no
  vars_files:
    - vars/aws.yml

  tasks:
    - name: Download secure variables from S3.
      s3: >
        aws_access_key={{ aws_access_key }}
        aws_secret_key={{ aws_secret_key }}
        bucket={{ s3_bucket }}
        object=/ansible/vars/secure.yml
        dest=vars/secure.yml
        mode=get
