---
- name: Ensure the .ssh directory has correct permissions.
  file: path=~/.ssh owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }} mode=700

- name: Ensure private keys in S3 are present.
  s3: >
    aws_access_key={{ aws_access_key }}
    aws_secret_key={{ aws_secret_key }}
    bucket={{ s3_bucket }}
    object=/ssh/{{ item }}
    dest=~/.ssh/{{ item }}
    overwrite=no
    mode=get
  with_items: private_keys

- name: Ensure private keys in the .ssh directory have the correct permissions.
  file: path=~/.ssh/{{ item }} owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }} mode=600
  with_items: private_keys

- name: Ensure public keys in S3 are present.
  s3: >
    aws_access_key={{ aws_access_key }}
    aws_secret_key={{ aws_secret_key }}
    bucket={{ s3_bucket }}
    object=/ssh/{{ item }}
    dest=~/.ssh/{{ item }}
    overwrite=no
    mode=get
  with_items: public_keys

- name: Ensure public keys in the .ssh directory have the correct permissions.
  file: path=~/.ssh/{{ item }} owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }} mode=644
  with_items: public_keys

- name: Ensure SSH config file is in place.
  copy: >
    src=config
    dest=~/.ssh
