---
- name: Template out user ~/.gitconfig.
  template:
    src: gitconfig.user.j2
    dest: ~/.gitconfig
    group: "{{ ansible_ssh_user }}"
    owner: "{{ ansible_ssh_user }}"

- name: Template out user ~/.gitignore_global.
  template:
    src: gitignore_global.j2
    dest: ~/.gitignore_global
    group: "{{ ansible_ssh_user }}"
    owner: "{{ ansible_ssh_user }}"