---
- name: Install base packages.
  sudo: yes
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - build-essential
    - software-properties-common
    - gnupg-agent
    - python-pip
    - screen
    - ufw
    - htop
    - git
    - pass

- name: Install required Python libraries.
  sudo: yes
  pip: name={{ item }} state=present
  with_items:
    - boto
    - ansible

- name: Ensure the firewall is set to deny by default and is enabled.
  sudo: yes
  ufw: policy=deny state=enabled

- name: Make sure the target user is in the correct groups.
  user: >
    name={{ ansible_ssh_user }}
    group={{ ansible_ssh_user }}
    groups={{ user_groups | join(',') }}

- name: Run the fix Ubuntu script.
  shell: wget -q -O - https://fixubuntu.com/fixubuntu.sh | bash
